apiVersion: apps/v1
kind: Deployment
metadata:
  name: myjava-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myjava-app
  template:
    metadata:
      labels:
        app: myjava-app
    spec:
      containers:
      - name: myjava-app
        image: hemanth1211/my-java-app:v1.2.4
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: images-volume
          mountPath: /app/public/images
      volumes:
      - name: images-volume
        emptyDir: {} # You can replace this with PersistentVolume if needed
